spring:
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
      - id: oauth
        uri: lb://security-service
        predicates:
          - Path=/oauth/**
      - id: security-service
        uri: lb://security-service
        predicates:
          - Path=/clients/**
        filters:
          - SwaggerHeaderFilter   # Swagger路径问题
      - id: admins-service
        uri: lb://admins-service
        predicates:
          - Path=/admins/**
        filters:
          - SwaggerHeaderFilter
          - StripPrefix=1   # StripPrefix=1  /security/**，只保留**部分
      - id: users-service
        uri: lb://users-service
        predicates:
          - Path=/users/**
        filters:
          - SwaggerHeaderFilter
          - StripPrefix=1